



CREATE SEQUENCE BNMSDSF01_SOFTWARE_SEQ START WITH 1 INCREMENT BY 1;


CREATE SEQUENCE BNMSDSF02_SERVICIO_SEQ START WITH 1 INCREMENT BY 1;


CREATE SEQUENCE BNMSDSF03_PERSONAL_SEQ START WITH 1 INCREMENT BY 1;
