CREATE OR REPLACE EDITIONABLE TRIGGER BNMSDSF01_SOFTWARE_TRIGGER
before INSERT ON BNMSDSF01_SOFTWARE
FOR EACH ROW
BEGIN
IF :new.F01_ID IS NULL THEN
    SELECT BNMSDSF01_SOFTWARE_SEQ.NEXTVAL INTO :NEW.F01_ID FROM dual;
     END IF;
END;
/



CREATE OR REPLACE EDITIONABLE TRIGGER BNMSDSF02_SERVICIO_TRIGGER
BEFORE INSERT ON BNMSDSF02_SERVICIO
FOR EACH ROW
BEGIN
    IF :NEW.F02_ID IS NULL THEN
        SELECT BNMSDSF02_SERVICIO_SEQ.NEXTVAL INTO :NEW.F02_ID FROM dual;
    END IF;
END;
/

CREATE OR REPLACE EDITIONABLE TRIGGER BNMSDSF03_PERSONAL_TRIGGER
BEFORE INSERT ON BNMSDSF03_PERSONAL
FOR EACH ROW
BEGIN
    IF :NEW.F03_ID IS NULL THEN
        SELECT BNMSDSF03_PERSONAL_SEQ.NEXTVAL INTO :NEW.F03_ID FROM dual;
    END IF;
END;
/
