ALTER TABLE BNMSDSF01_APLICATIVO
ADD (F03_PERSONAL_ID NUMBER,
     CONSTRAINT FK_BNMSDSF02_PERSONAL_APLICATIVO FOREIGN KEY (F03_PERSONAL_ID) REFERENCES BNMSDSF03_PERSONAL(F03_ID));
	 
	 
	 
ALTER TABLE BNMSDSF02_SERVICIO
ADD (F03_PERSONAL_ID NUMBER,
     CONSTRAINT FK_BNMSDSF02_PERSONAL_SERVICIO FOREIGN KEY (F03_PERSONAL_ID) REFERENCES BNMSDSF03_PERSONAL(F03_ID));